import { create } from "zustand";

export const useArticleStore = create((set) => ({
  articles: [
    {
      id: 1,
      title: "Getting Started with Web Development",
      slug: "getting-started-with-web-development",
      excerpt:
        "Learn the basics of web development and how to build your first website.",
      content:
        "Web development is the process of building and maintaining websites. It includes HTML, CSS, JavaScript, and modern frameworks.",
      author: "John Doe",
      category: "Web Development",
      image: "https://picsum.photos/seed/article1/800/500",
      publishedAt: "2024-01-05",
      readTime: "5 min",
    },
    {
      id: 2,
      title: "Why JavaScript Is Still Dominating",
      slug: "why-javascript-is-still-dominating",
      excerpt:
        "JavaScript remains the most popular language for frontend and backend development.",
      content:
        "JavaScript powers the modern web. From browsers to servers, it continues to evolve and improve.",
      author: "Sara Smith",
      category: "JavaScript",
      image: "https://picsum.photos/seed/article2/800/500",
      publishedAt: "2024-01-10",
      readTime: "6 min",
    },
    {
      id: 3,
      title: "Understanding React Hooks",
      slug: "understanding-react-hooks",
      excerpt: "Hooks changed how we write React components.",
      content:
        "React Hooks allow you to use state and lifecycle features without writing class components.",
      author: "Michael Brown",
      category: "React",
      image: "https://picsum.photos/seed/article3/800/500",
      publishedAt: "2024-01-15",
      readTime: "7 min",
    },
    {
      id: 4,
      title: "CSS Tips for Clean UI Design",
      slug: "css-tips-for-clean-ui-design",
      excerpt: "Simple CSS techniques to improve your UI design.",
      content:
        "Good UI design focuses on spacing, typography, and consistency.",
      author: "Emily Johnson",
      category: "CSS",
      image: "https://picsum.photos/seed/article4/800/500",
      publishedAt: "2024-01-18",
      readTime: "4 min",
    },
    {
      id: 5,
      title: "How APIs Work",
      slug: "how-apis-work",
      excerpt: "APIs are the backbone of modern applications.",
      content:
        "APIs allow different systems to communicate using standard protocols.",
      author: "David Wilson",
      category: "Backend",
      image: "https://picsum.photos/seed/article5/800/500",
      publishedAt: "2024-01-22",
      readTime: "6 min",
    },
    {
      id: 6,
      title: "Introduction to TypeScript",
      slug: "introduction-to-typescript",
      excerpt: "TypeScript helps catch errors before runtime.",
      content:
        "TypeScript adds static typing to JavaScript for safer development.",
      author: "Olivia Taylor",
      category: "TypeScript",
      image: "https://picsum.photos/seed/article6/800/500",
      publishedAt: "2024-01-25",
      readTime: "5 min",
    },
    {
      id: 7,
      title: "Building Responsive Layouts",
      slug: "building-responsive-layouts",
      excerpt: "Make your website look good on all devices.",
      content:
        "Responsive design uses flexible layouts, media queries, and modern CSS.",
      author: "Daniel Anderson",
      category: "Frontend",
      image: "https://picsum.photos/seed/article7/800/500",
      publishedAt: "2024-01-28",
      readTime: "6 min",
    },
    {
      id: 8,
      title: "Next.js for Beginners",
      slug: "nextjs-for-beginners",
      excerpt: "Why Next.js is popular for modern web apps.",
      content: "Next.js provides server-side rendering and better performance.",
      author: "Sophia Thomas",
      category: "Next.js",
      image: "https://picsum.photos/seed/article8/800/500",
      publishedAt: "2024-02-01",
      readTime: "7 min",
    },
    {
      id: 9,
      title: "SEO Basics for Developers",
      slug: "seo-basics-for-developers",
      excerpt: "Improve your website visibility on search engines.",
      content: "SEO involves performance, content structure, and metadata.",
      author: "James Martinez",
      category: "SEO",
      image: "https://picsum.photos/seed/article9/800/500",
      publishedAt: "2024-02-05",
      readTime: "5 min",
    },
    {
      id: 10,
      title: "Using Git Like a Pro",
      slug: "using-git-like-a-pro",
      excerpt: "Master version control with Git.",
      content: "Git helps teams collaborate and track code changes.",
      author: "Ava Garcia",
      category: "Tools",
      image: "https://picsum.photos/seed/article10/800/500",
      publishedAt: "2024-02-08",
      readTime: "6 min",
    },
    {
      id: 11,
      title: "Clean Code Principles",
      slug: "clean-code-principles",
      excerpt: "Write code that is easy to read and maintain.",
      content: "Clean code focuses on readability, naming, and simplicity.",
      author: "Robert Lee",
      category: "Best Practices",
      image: "https://picsum.photos/seed/article11/800/500",
      publishedAt: "2024-02-12",
      readTime: "6 min",
    },
    {
      id: 12,
      title: "Understanding REST vs GraphQL",
      slug: "rest-vs-graphql",
      excerpt: "Choosing the right API architecture.",
      content: "REST and GraphQL solve different problems in data fetching.",
      author: "Mia Clark",
      category: "Backend",
      image: "https://picsum.photos/seed/article12/800/500",
      publishedAt: "2024-02-15",
      readTime: "7 min",
    },
    {
      id: 13,
      title: "Web Performance Optimization",
      slug: "web-performance-optimization",
      excerpt: "Speed matters for user experience.",
      content: "Optimize images, code splitting, and caching for faster sites.",
      author: "William Lewis",
      category: "Performance",
      image: "https://picsum.photos/seed/article13/800/500",
      publishedAt: "2024-02-18",
      readTime: "6 min",
    },
    {
      id: 14,
      title: "Authentication Explained",
      slug: "authentication-explained",
      excerpt: "Understand how login systems work.",
      content:
        "Authentication verifies user identity using tokens or sessions.",
      author: "Charlotte Walker",
      category: "Security",
      image: "https://picsum.photos/seed/article14/800/500",
      publishedAt: "2024-02-22",
      readTime: "5 min",
    },
    {
      id: 15,
      title: "State Management in React",
      slug: "state-management-in-react",
      excerpt: "Managing state efficiently in large apps.",
      content: "State management tools help organize complex data flows.",
      author: "Benjamin Hall",
      category: "React",
      image: "https://picsum.photos/seed/article15/800/500",
      publishedAt: "2024-02-25",
      readTime: "7 min",
    },
    {
      id: 16,
      title: "Introduction to Docker",
      slug: "introduction-to-docker",
      excerpt: "Simplify deployments with containers.",
      content: "Docker packages applications with all dependencies.",
      author: "Amelia Young",
      category: "DevOps",
      image: "https://picsum.photos/seed/article16/800/500",
      publishedAt: "2024-03-01",
      readTime: "6 min",
    },
    {
      id: 17,
      title: "Building Dark Mode UI",
      slug: "building-dark-mode-ui",
      excerpt: "Dark mode improves UX and accessibility.",
      content: "Use CSS variables and system preferences for dark mode.",
      author: "Lucas Hernandez",
      category: "UI/UX",
      image: "https://picsum.photos/seed/article17/800/500",
      publishedAt: "2024-03-05",
      readTime: "4 min",
    },
    {
      id: 18,
      title: "Database Indexing Explained",
      slug: "database-indexing-explained",
      excerpt: "Improve query performance with indexes.",
      content: "Indexes speed up data retrieval in databases.",
      author: "Harper King",
      category: "Database",
      image: "https://picsum.photos/seed/article18/800/500",
      publishedAt: "2024-03-08",
      readTime: "6 min",
    },
    {
      id: 19,
      title: "Error Handling Best Practices",
      slug: "error-handling-best-practices",
      excerpt: "Handle errors gracefully in applications.",
      content: "Good error handling improves stability and user trust.",
      author: "Henry Wright",
      category: "Best Practices",
      image: "https://picsum.photos/seed/article19/800/500",
      publishedAt: "2024-03-12",
      readTime: "5 min",
    },
    {
      id: 20,
      title: "Deploying Your First App",
      slug: "deploying-your-first-app",
      excerpt: "From local development to production.",
      content: "Deployment involves hosting, CI/CD, and environment setup.",
      author: "Ella Lopez",
      category: "Deployment",
      image: "https://picsum.photos/seed/article20/800/500",
      publishedAt: "2024-03-15",
      readTime: "6 min",
    },
  ],
  addArticle: (article) =>
    set((state) => ({
      articles: [...state.articles, { ...article, id: Date.now() }],
    })),

  deleteArticle: (id) =>
    set((state) => ({
      articles: state.articles.filter((a) => a.id !== id),
    })),

  editArticle: (id, updatedArticle) =>
    set((state) => ({
      articles: state.articles.map((a) =>
        a.id === id ? { ...a, ...updatedArticle } : a
      ),
    })),
}));
